### PR TITLE
added bot comments 🙌🏻

### PR DESCRIPTION
**Pull request by archanaserver**
Hey, @Tlazypanda 👋 I have made some changes for bot comments, please check it out. And let me know for any further changes. Happy to contribute more.🤗

Thanks! :)

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@archanaserver Guess we have a live demo of what you just created 😂 🔥

**Comment by archanaserver** [comment]
Yeah looks cool @Tlazypanda but I'm just thinking why everything got merged in a single line? Indentation is not working here I guess. Let me try to fix it. 🙌🏻

**Comment by Tlazypanda** [comment]
@archanaserver Yeah that needs a bit of work but the content looks great!! :tada: Also I was wondering if there are more points that we can add to the "Help others take their first step section" :sweat_smile:

**Comment by archanaserver** [comment]
> @archanaserver Yeah that needs a bit of work but the content looks great!! 🎉 Also I was wondering if there are more points that we can add to the "Help others take their first step section" 😅

Yes @Tlazypanda, I was thinking about the same. I will try to draft few points by tomorrow and create PR on that too.🙌🏻

**Pull request merged**
